name: Deploy Next.js App to Vercel
run-name: ${{ github.actor }} is deploying to Vercel 🚀

on: [push]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clone wisp-modules into public/modules
        run: |
          mkdir -p public/modules
          git clone --depth 1 https://github.com/EthanHazel/wisp-modules.git temp_wisp_modules
          mv temp_wisp_modules/* temp_wisp_modules/.* public/modules/ 2>/dev/null || true
          rm -rf temp_wisp_modules
          echo "📂 Successfully cloned wisp-modules into the public/modules folder."

      - name: Verify Cloned Files
        run: ls -la public/modules

      - name: Commit Cloned Files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add public/modules
          git commit -m "Auto-update: Cloned wisp-modules into public/modules" || echo "No changes to commit"
          git push

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel pull --yes --token ${{ secrets.VERCEL_TOKEN }}
          vercel build --token ${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }}
